### ISSUE TITLE
Project Git history?

### ISSUE THREAD

**Issue by quicksketch** [backdrop-contrib/node_clone#1]
Hi @biolithic! This is great to have clone.module for Backdrop!

This came from the D7 module it looks like, but the project history was not maintained. Before development goes further, could you start with a clone of the D7 module, overlay the Backdrop port on top of it, then commit/force-push the module to this repository? Maintaining the history keeps attribution in place and makes it easier to understand changes.

**Comment by biolithic** [comment]
I think I did before?

https://github.com/backdrop-contrib/node_clone/commits/7.x-1.x

**Comment by quicksketch** [comment]
Oh! Sorry every file being modified at the exact same timestamp threw me off. Thanks @biolithic!
