### ISSUE TITLE
clone or node_clone?

### ISSUE THREAD

**Issue by klonos** [backdrop-contrib/node_clone#2]
I was under the impression that the convention was that modules have a `module_name\module_name.info` structure, but this one is `node_clone\clone.info`. Why is that (why not `node_clone\node_clone.info`)?

**Comment by biolithic** [comment]
I followed the Drupal port directly:

https://www.drupal.org/project/node_clone

 I feel that if you were to port your Drupal site to Backdrop, the names
should stay the same to avoid any conflict.  It's possible that the
original was wrong, but it is rather popular, so I'm not going to rock the
boat on this one.

**Comment by klonos** [comment]
Fair enough.
