### ISSUE TITLE
Feature request: Clone action in dropbutton

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/node_clone#7]
It would be nice to see the clone button as a drop down option in the action dropbutton:

![screen shot 2019-01-22 at 11 38 41 am](https://user-images.githubusercontent.com/871421/51554219-5ab10d80-1e3a-11e9-92e2-7930f6f2239a.jpg)

**Comment by robertgarrigos** [comment]
This is already implemented.

**Comment by robertgarrigos** [comment]
Sorry, i think I just missundertood you. the dropbutton is not implemented.

**Comment by robertgarrigos** [comment]
Yes, it is implemented. It took me a while to get it. 
![Fullscreen_17_10_24__09_41](https://github.com/user-attachments/assets/2b201f53-20e6-431a-905a-90db7f0b881d)
